language: python

after_success:
    - bash <(curl -s https://codecov.io/bash)

# Install the codecov pip dependency
install:
    - pip install cython
    - pip install -r requirements.txt

script:
    - tox
