language: python

cache: pip

python:
    - '3.5'
    - '3.6'
    - '3.7'
    - '3.8'

# after_success:
#     - bash <(curl -s https://codecov.io/bash)

before_install:
    - sudo apt-get update
    - sudo apt-get install libtag1-dev

# Install the codecov pip dependency
install:
    - pip install cython tox coveralls
    - pip install -r requirements.txt

script:
    - tox -e coverage
    - coveralls
